exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('kanye')
    .del()
    .then(() => {
      return knex('kanye').insert([
        {
          id: 1,
          name: 'Kanye West',
          album_title: 'The College Dropout',
          release_year: 2004,
          genre: 'hip-hop',
          tracklist: 21,
          length: 76.13,
          cover_image: '/images/TCD.jpeg',
        },
        {
          id: 2,
          name: 'Kanye West',
          album_title: 'Late Registration',
          release_year: 2005,
          genre: 'hip-hop',
          tracklist: 21,
          length: 70.25,
          cover_image: '/images/LR.jpeg',
        },
        {
          id: 3,
          name: 'Kanye West',
          album_title: 'Graduation',
          release_year: 2007,
          genre: 'hip-hop',
          tracklist: 13,
          length: 51.23,
          cover_image: '/images/GR.jpeg',
        },
        {
          id: 4,
          name: 'Kanye West',
          album_title: '808s and Heartbreaks',
          release_year: 2008,
          genre: 'hip-hop',
          tracklist: 12,
          length: 51.58,
          cover_image: '/images/808s.jpeg',
        },
        {
          id: 5,
          name: 'Kanye West',
          album_title: 'My Beautiful Dark Twisted Fantasy',
          release_year: 2010,
          genre: 'hip-hop',
          tracklist: 13,
          length: 68.39,
          cover_image: '/images/MBDTF.jpeg',
        },
        {
          id: 6,
          name: 'Kanye West',
          album_title: 'Watch The Throne',
          release_year: 2011,
          genre: 'hip-hop',
          tracklist: 16,
          length: 46.12,
          cover_image: '/images/WTT.jpeg',
        },
        {
          id: 7,
          name: 'Kanye West',
          album_title: 'Cruel Summer',
          release_year: 2012,
          genre: 'hip-hop',
          tracklist: 12,
          length: '54.31',
          cover_image: '/images/CS.jpeg',
        },
        {
          id: 8,
          name: 'Kanye West',
          album_title: 'Yeezus',
          release_year: 2013,
          genre: 'hip-hop',
          tracklist: 10,
          length: 40.01,
          cover_image: '/images/YEEZUS.jpeg',
        },
        {
          id: 9,
          name: 'Kanye West',
          album_title: 'The Life of Pablo',
          release_year: 2016,
          genre: 'hip-hop',
          tracklist: 20,
          length: 66.01,
          cover_image: '/images/TLOP.jpeg',
        },
        {
          id: 10,
          name: 'Kanye West',
          album_title: 'Ye',
          release_year: 2018,
          genre: 'hip-hop',
          tracklist: 7,
          length: 23.41,
          cover_image: '/images/YE.jpeg',
        },
        {
          id: 11,
          name: 'Kanye West',
          album_title: 'Kids See Ghosts',
          release_year: 2018,
          genre: 'hip-hop',
          tracklist: 7,
          length: 23.5,
          cover_image: '/images/KSG.jpeg',
        },
        {
          id: 12,
          name: 'Kanye West',
          album_title: 'Yandhi',
          release_year: 2019,
          genre: 'hip-hop',
          tracklist: 11,
          length: 27.04,
          cover_image: '/images/yandhi.jpeg',
        },
        {
          id: 13,
          name: 'Kanye West',
          album_title: 'Jesus is King',
          release_year: 2019,
          genre: 'hip-hop',
          tracklist: 11,
          length: 27.04,
          cover_image: '/images/JIK.jpg',
        },
        {
          id: 14,
          name: 'Kanye West',
          album_title: 'Donda',
          release_year: 2021,
          genre: 'hip-hop',
          tracklist: 27,
          length: 108.48,
          cover_image: '/images/donda1.jpeg',
        },
        {
          id: 15,
          name: 'Kanye West',
          album_title: 'Donda 2',
          release_year: 2022,
          genre: 'hip-hop',
          tracklist: 16,
          length: 47.22,
          cover_image: '/images/DONDA.jpeg',
        },
      ])
    })
}
