exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('twice')
    .del()
    .then(() => {
      return knex('twice').insert([
        {
          id: 1,
          name: 'Twice',
          album_title: 'The Story Begins',
          release_year: 2015,
          genre: 'kpop',
          tracklist: 6,
          length: 19.55,
        },
        {
          id: 2,
          name: 'Twice',
          album_title: 'Page Two',
          release_year: 2016,
          genre: 'kpop',
          tracklist: 7,
          length: 23.51,
        },
        {
          id: 3,
          name: 'Twice',
          album_title: 'Twicecoaster: Lane 1',
          release_year: 2016,
          genre: 'kpop',
          tracklist: 7,
          length: 22.48,
        },
        {
          id: 4,
          name: 'Twice',
          album_title: 'Twicecoaster: Lane 2',
          release_year: 2017,
          genre: 'kpop',
          tracklist: 9,
          length: 29.55,
        },
        {
          id: 5,
          name: 'Twice',
          album_title: 'Signal',
          release_year: 2017,
          genre: 'kpop',
          tracklist: 6,
          length: 19.45,
        },
        {
          id: 6,
          name: 'Twice',
          album_title: 'Twicetagram',
          release_year: 2017,
          genre: 'kpop',
          tracklist: 13,
          length: 44.16,
        },
        {
          id: 7,
          name: 'Twice',
          album_title: 'Merry & Happy',
          release_year: 2017,
          genre: 'kpop',
          tracklist: 15,
          length: 50.38,
        },
        {
          id: 8,
          name: 'Twice',
          album_title: 'What is Love?',
          release_year: 2018,
          genre: 'kpop',
          tracklist: 6,
          length: 20.06,
        },
        {
          id: 9,
          name: 'Twice',
          album_title: 'Summer Nights',
          release_year: 2018,
          genre: 'kpop',
          tracklist: 9,
          length: 29.44,
        },
        {
          id: 10,
          name: 'Twice',
          album_title: 'Yes or Yes',
          release_year: 2018,
          genre: 'kpop',
          tracklist: 7,
          length: 24.02,
        },
        {
          id: 11,
          name: 'Twice',
          album_title: 'The Year of "Yes"',
          release_year: 2019,
          genre: 'kpop',
          tracklist: 9,
          length: 31.23,
        },
        {
          id: 12,
          name: 'Twice',
          album_title: 'Fancy You',
          release_year: 2019,
          genre: 'kpop',
          tracklist: 6,
          length: 18.5,
        },
        {
          id: 13,
          name: 'Twice',
          album_title: 'Feel Special',
          release_year: 2019,
          genre: 'kpop',
          tracklist: 7,
          length: 23.26,
        },
        {
          id: 14,
          name: 'Twice',
          album_title: 'More & More',
          release_year: 2020,
          genre: 'kpop',
          tracklist: 7,
          length: 22.15,
        },
        {
          id: 15,
          name: 'Twice',
          album_title: 'Eyes Wide Open',
          release_year: 2020,
          genre: 'kpop',
          tracklist: 13,
          length: 43.24,
        },
        {
          id: 16,
          name: 'Twice',
          album_title: 'Taste of Love',
          release_year: 2021,
          genre: 'kpop',
          tracklist: 7,
          length: 17.21,
        },
        {
          id: 17,
          name: 'Twice',
          album_title: 'Formula of Love: O+T=<3',
          release_year: 2021,
          genre: 'kpop',
          tracklist: 16,
          length: 48.31,
        },
      ])
    })
}
